spring.application.name=booking-service
spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus
spring.data.mongodb.database=smartcampus
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123